
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rohit
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        new_member_menu = new javax.swing.JMenu();
        delete_and_update_menu = new javax.swing.JMenu();
        list_of_member_menu = new javax.swing.JMenu();
        payment_menu = new javax.swing.JMenu();
        logout_menu = new javax.swing.JMenu();
        exit_menu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_bg2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 51));

        new_member_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_member.png"))); // NOI18N
        new_member_menu.setText("New Member");
        new_member_menu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        new_member_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_member_menuMouseClicked(evt);
            }
        });
        jMenuBar1.add(new_member_menu);

        delete_and_update_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_and_update.png"))); // NOI18N
        delete_and_update_menu.setText("Delete & Update Member");
        delete_and_update_menu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delete_and_update_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_and_update_menuMouseClicked(evt);
            }
        });
        jMenuBar1.add(delete_and_update_menu);

        list_of_member_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list_of_members.png"))); // NOI18N
        list_of_member_menu.setText("List Of Member");
        list_of_member_menu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        list_of_member_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_of_member_menuMouseClicked(evt);
            }
        });
        jMenuBar1.add(list_of_member_menu);

        payment_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payment.png"))); // NOI18N
        payment_menu.setText("Payment");
        payment_menu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        payment_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payment_menuMouseClicked(evt);
            }
        });
        jMenuBar1.add(payment_menu);

        logout_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout_menu.setText("Logout");
        logout_menu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logout_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_menuMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout_menu);

        exit_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exit_menu.setText("Exit");
        exit_menu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exit_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_menuMouseClicked(evt);
            }
        });
        jMenuBar1.add(exit_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_menuMouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really wants to logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logout_menuMouseClicked

    private void exit_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_menuMouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really wants to Exit","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
        }
    }//GEN-LAST:event_exit_menuMouseClicked

    private void new_member_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_member_menuMouseClicked
        new NewMember().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_new_member_menuMouseClicked

    private void delete_and_update_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_and_update_menuMouseClicked
        // TODO add your handling code here:
        new Update_and_delete().setVisible(true);
    }//GEN-LAST:event_delete_and_update_menuMouseClicked

    private void list_of_member_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_of_member_menuMouseClicked
        // TODO add your handling code here:
        new List_of_member().setVisible(true);
    }//GEN-LAST:event_list_of_member_menuMouseClicked

    private void payment_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payment_menuMouseClicked
        // TODO add your handling code here:
        new payment().setVisible(true);
    }//GEN-LAST:event_payment_menuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu delete_and_update_menu;
    private javax.swing.JMenu exit_menu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu list_of_member_menu;
    private javax.swing.JMenu logout_menu;
    private javax.swing.JMenu new_member_menu;
    private javax.swing.JMenu payment_menu;
    // End of variables declaration//GEN-END:variables
}
