/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rohit
 */
import java.awt.Color;
import java.lang.String;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gmail_tf = new javax.swing.JTextField();
        pass_tf = new javax.swing.JPasswordField();
        login_button = new javax.swing.JButton();
        show_pass_cb = new javax.swing.JCheckBox();
        close_login_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("login_frame"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gmail_tf.setBackground(new java.awt.Color(204, 204, 255));
        gmail_tf.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        gmail_tf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        gmail_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gmail_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gmail_tfFocusLost(evt);
            }
        });
        gmail_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmail_tfActionPerformed(evt);
            }
        });
        getContentPane().add(gmail_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 350, 40));

        pass_tf.setBackground(new java.awt.Color(204, 204, 255));
        pass_tf.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        pass_tf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        pass_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_tfFocusLost(evt);
            }
        });
        pass_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_tfActionPerformed(evt);
            }
        });
        getContentPane().add(pass_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 360, 40));

        login_button.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        login_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 150, 40));

        show_pass_cb.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        show_pass_cb.setForeground(new java.awt.Color(255, 255, 255));
        show_pass_cb.setText("Show  Password");
        show_pass_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_pass_cbActionPerformed(evt);
            }
        });
        getContentPane().add(show_pass_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 170, 60));

        close_login_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        close_login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_login_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(close_login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, -1, -1));

        reset_button.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        reset_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        reset_button.setText("Reset");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(reset_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 150, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_bg.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gmail_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmail_tfActionPerformed
        pass_tf.setEchoChar('•');        // TODO add your handling code here:
    }//GEN-LAST:event_gmail_tfActionPerformed

    private void gmail_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gmail_tfFocusGained
        if(gmail_tf.getText().equals("Enter Gmail id "))
        {
            gmail_tf.setText("");
            gmail_tf.setForeground(new java.awt.Color(0,0,0));
            gmail_tf.setBackground(new java.awt.Color(255,255,255));
        }
    }//GEN-LAST:event_gmail_tfFocusGained

    private void gmail_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gmail_tfFocusLost
        if(gmail_tf.getText().equals(""))
        {
            gmail_tf.setText("Enter Gmail id ");
            gmail_tf.setForeground(new java.awt.Color(255,255,255));
            
            gmail_tf.setBackground(new java.awt.Color(153,153,153));
            
        }
    }//GEN-LAST:event_gmail_tfFocusLost

    private void pass_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_tfFocusLost
        if(pass_tf.getText().equals(""))
        {
            
            pass_tf.setText("Enter password here ");
            pass_tf.setForeground(Color.WHITE);
            pass_tf.setBackground(new java.awt.Color(153,153,153));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_pass_tfFocusLost

    private void pass_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_tfFocusGained
       if(pass_tf.getText().equals("Enter password here "))
       {
           pass_tf.setText("");
           pass_tf.setForeground(new java.awt.Color(0,0,0));
           pass_tf.setBackground(Color.WHITE);
           
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_tfFocusGained

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        if(gmail_tf.getText().equals("admin") && pass_tf.getText().equals("1234"))
        {
            setVisible(false);
            new Home().setVisible(true);
        }
        else 
        {
            JOptionPane.showMessageDialog(null,"Incorrect gmail or password");
            reset_buttonActionPerformed(evt);
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void show_pass_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_pass_cbActionPerformed
        if(show_pass_cb.isSelected())
        {
            pass_tf.setEchoChar((char)0);
        }
        else
        {
            pass_tf.setEchoChar('•');
        }
// TODO add your handling code here:
    }//GEN-LAST:event_show_pass_cbActionPerformed

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
            pass_tf.setText("");
            gmail_tf.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_reset_buttonActionPerformed

    private void close_login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_login_buttonActionPerformed
         int a =JOptionPane.showConfirmDialog(null, "Do you really want to Exit from Application","Select",JOptionPane.YES_NO_OPTION);
         if(a ==0)
         {
             System.exit(a);
         }
         
            // TODO add your handling code here:
    }//GEN-LAST:event_close_login_buttonActionPerformed

    private void pass_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_tfActionPerformed
            pass_tf.setEchoChar('•');        // TODO add your handling code here:
    }//GEN-LAST:event_pass_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                 
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_login_button;
    private javax.swing.JTextField gmail_tf;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField pass_tf;
    private javax.swing.JButton reset_button;
    private javax.swing.JCheckBox show_pass_cb;
    // End of variables declaration//GEN-END:variables
}
