
import javax.swing.JOptionPane;
import Project.ConnectionProvider;
import java.sql.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rohit
 */
public class NewMember extends javax.swing.JFrame {

    /**
     * Creates new form NewMember
     */
    public NewMember() {
        initComponents();
        try 
        {
            int id =1;
            String str = String.valueOf(id);
            member_id_no.setText(str);
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select max(id) from member ");
            while(rs.next())
            {
                id = rs.getInt(1);
                id++;
                String str1 = String.valueOf(id);
                member_id_no.setText(str1);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        close_button = new javax.swing.JButton();
        member_if_label = new javax.swing.JLabel();
        member_id_no = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        mobile_label = new javax.swing.JLabel();
        email_tf = new javax.swing.JTextField();
        mobile_tf = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        gender_label = new javax.swing.JLabel();
        gender_combobox = new javax.swing.JComboBox<>();
        father_label = new javax.swing.JLabel();
        father_tf = new javax.swing.JTextField();
        mother_label = new javax.swing.JLabel();
        mother_tf = new javax.swing.JTextField();
        Batch_timing_label = new javax.swing.JLabel();
        batch_timing_combobox = new javax.swing.JComboBox<>();
        Aadhar_label = new javax.swing.JLabel();
        aadhar_tf = new javax.swing.JTextField();
        age_label = new javax.swing.JLabel();
        age_tf = new javax.swing.JTextField();
        amount_pay_label = new javax.swing.JLabel();
        amount_pay_tf = new javax.swing.JTextField();
        title_label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        member_if_label.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        member_if_label.setForeground(new java.awt.Color(0, 102, 204));
        member_if_label.setText("Member ID: ");

        member_id_no.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        member_id_no.setForeground(new java.awt.Color(255, 0, 0));
        member_id_no.setText("00");

        name_label.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        name_label.setForeground(new java.awt.Color(0, 102, 204));
        name_label.setText("Name:-");

        name_tf.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        name_tf.setForeground(new java.awt.Color(0, 102, 204));
        name_tf.setMinimumSize(new java.awt.Dimension(64, 25));
        name_tf.setPreferredSize(new java.awt.Dimension(75, 25));
        name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_tfActionPerformed(evt);
            }
        });

        mobile_label.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        mobile_label.setForeground(new java.awt.Color(0, 102, 204));
        mobile_label.setText("Mobile Number :");

        email_tf.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        email_tf.setForeground(new java.awt.Color(0, 102, 204));
        email_tf.setPreferredSize(new java.awt.Dimension(75, 31));

        mobile_tf.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        mobile_tf.setForeground(new java.awt.Color(0, 102, 204));
        mobile_tf.setPreferredSize(new java.awt.Dimension(75, 25));

        email_label.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        email_label.setForeground(new java.awt.Color(0, 102, 204));
        email_label.setText("Email:");

        gender_label.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        gender_label.setForeground(new java.awt.Color(0, 102, 204));
        gender_label.setText("Gender");

        gender_combobox.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        gender_combobox.setForeground(new java.awt.Color(0, 102, 204));
        gender_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        gender_combobox.setPreferredSize(new java.awt.Dimension(75, 31));
        gender_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_comboboxActionPerformed(evt);
            }
        });

        father_label.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        father_label.setForeground(new java.awt.Color(0, 102, 204));
        father_label.setText("Father Name:");

        father_tf.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        father_tf.setForeground(new java.awt.Color(0, 102, 204));
        father_tf.setPreferredSize(new java.awt.Dimension(75, 25));

        mother_label.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        mother_label.setForeground(new java.awt.Color(0, 102, 204));
        mother_label.setText("Mother Name:");

        mother_tf.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        mother_tf.setForeground(new java.awt.Color(0, 102, 204));
        mother_tf.setPreferredSize(new java.awt.Dimension(75, 25));

        Batch_timing_label.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        Batch_timing_label.setForeground(new java.awt.Color(0, 102, 204));
        Batch_timing_label.setText("Batch  Timing:");

        batch_timing_combobox.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        batch_timing_combobox.setForeground(new java.awt.Color(0, 102, 204));
        batch_timing_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "5:00 AM - 11:00 AM", "4:00PM - 10:00PM" }));
        batch_timing_combobox.setPreferredSize(new java.awt.Dimension(75, 25));

        Aadhar_label.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        Aadhar_label.setForeground(new java.awt.Color(0, 102, 204));
        Aadhar_label.setText("Aadhar Card No. (Unique Identity)");

        aadhar_tf.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        aadhar_tf.setForeground(new java.awt.Color(0, 102, 204));
        aadhar_tf.setPreferredSize(new java.awt.Dimension(75, 31));

        age_label.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        age_label.setForeground(new java.awt.Color(0, 102, 204));
        age_label.setText("Age:");

        age_tf.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        age_tf.setForeground(new java.awt.Color(0, 102, 204));
        age_tf.setPreferredSize(new java.awt.Dimension(75, 31));

        amount_pay_label.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        amount_pay_label.setForeground(new java.awt.Color(0, 102, 204));
        amount_pay_label.setText("Amount to Pay/Month");

        amount_pay_tf.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        amount_pay_tf.setForeground(new java.awt.Color(0, 102, 204));
        amount_pay_tf.setPreferredSize(new java.awt.Dimension(75, 25));

        title_label.setFont(new java.awt.Font("Calibri Light", 0, 48)); // NOI18N
        title_label.setForeground(new java.awt.Color(0, 0, 51));
        title_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_member.png"))); // NOI18N
        title_label.setText("New Member");

        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(close_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(41, 41, 41)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(father_tf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(father_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mobile_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(member_if_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(member_id_no, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(name_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name_tf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(email_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mobile_tf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(email_tf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gender_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender_combobox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mother_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mother_tf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Batch_timing_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(batch_timing_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Aadhar_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(age_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(age_tf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(amount_pay_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(amount_pay_tf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aadhar_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(close_button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(member_if_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(member_id_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mother_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mother_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile_label)
                    .addComponent(Batch_timing_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batch_timing_combobox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_label)
                    .addComponent(Aadhar_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aadhar_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age_label)
                    .addComponent(gender_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(father_label)
                    .addComponent(amount_pay_label))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(father_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount_pay_tf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(167, 167, 167))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        setVisible(false);
        
           // TODO add your handling code here:
    }//GEN-LAST:event_close_buttonActionPerformed

    private void name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_tfActionPerformed

    private void gender_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender_comboboxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new NewMember().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = member_id_no.getText();
        String name = name_tf.getText();
        String gmail = email_tf.getText();
        String mobile_no = mobile_tf.getText();
        String gender = (String)gender_combobox.getSelectedItem();
        String fatherName = father_tf.getText();
        String motherName = mother_tf.getText();
        String gymTime = (String)batch_timing_combobox.getSelectedItem();
        String aadhar_no = aadhar_tf.getText();
        String age = age_tf.getText();
        String amount = amount_pay_tf.getText();
        try 
        {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("insert into member values (?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1,id);
            ps.setString(2,name);
            ps.setString(3,mobile_no);
            ps.setString(4,gmail);
            ps.setString(5,gender);
            ps.setString(6,fatherName);
            ps.setString(7,motherName);
            ps.setString(8,gymTime);
            ps.setString(9,aadhar_no);
            ps.setString(10,age);
            ps.setString(11,amount);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Successfully saved");
            setVisible(false);
            new NewMember().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aadhar_label;
    private javax.swing.JLabel Batch_timing_label;
    private javax.swing.JTextField aadhar_tf;
    private javax.swing.JLabel age_label;
    private javax.swing.JTextField age_tf;
    private javax.swing.JLabel amount_pay_label;
    private javax.swing.JTextField amount_pay_tf;
    private javax.swing.JComboBox<String> batch_timing_combobox;
    private javax.swing.JButton close_button;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_tf;
    private javax.swing.JLabel father_label;
    private javax.swing.JTextField father_tf;
    private javax.swing.JComboBox<String> gender_combobox;
    private javax.swing.JLabel gender_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel member_id_no;
    private javax.swing.JLabel member_if_label;
    private javax.swing.JLabel mobile_label;
    private javax.swing.JTextField mobile_tf;
    private javax.swing.JLabel mother_label;
    private javax.swing.JTextField mother_tf;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_tf;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
}
